name: Trigger Deploy on Infrastructure

on:
    push:
        branches:
            - master

jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Dispatch deploy event to infrastructure repo
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.REPO_DISPATCH_PAT }}
                  repository: angrystrike/imager-infrastructure
                  event-type: deploy-monorepo
                  client-payload: '{"service": "view-service", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
